### ISSUE TITLE
"Members" not ready for translation

### ISSUE THREAD

**Issue by Admonstrator** [stoo2000/membermap#11]
Hi there,

the string "Members" isn't ready for translation.
btw: The last update was really impressive!

Nice work, keep on rockin'

**Comment by MartinAronsen** [comment]
You mean the string assign to the members layer group? That's translatable. Search for "membermap_overlay_members".

**Comment by Admonstrator** [comment]
Damn, you're right. I looked up the keys by using the "show keys instead of strings" function and it didn't showed up as a key ... anyway, thanks!
