### ISSUE TITLE
Integration with Rules and/or Calendar App

### ISSUE THREAD

**Issue by Admonstrator** [stoo2000/membermap#12]
Hi there,

a short idea about the next version of membermap:
It would be nice if membermap could interact with the Automation Rules App (https://invisionpower.com/files/file/7368-automation-rules-lite/) so If you update your location you can run a rule for that. Not necessary but would be nice.

Because we are using the IPS built-in calendar app for event management it would be nice if membermap could import events (with locations) to display them on the map. So we don't have to create a custom marker for every event ...

**Comment by MartinAronsen** [comment]
Is integration with Rules still a wish? 

And do you want the app to import the calendar events as custom markers, or just pull the event from the calendar app, and link to the event view? Assume the latter, as it won't make sense to duplicate that data.

**Comment by Admonstrator** [comment]
Would be nice if the last method would work - if not the first one would be OK too.

**Comment by MartinAronsen** [comment]
Changing the thought of this. Instead of going out and fetching the data from all the various apps, I'll make an application extension instead. That way Member Map will connect to the extension in the 3rd party apps.

**Comment by Admonstrator** [comment]
Sounds great, I'm pretty excited about this feature.
