### ISSUE TITLE
"Why don't you submit the first one?"-Button broken

### ISSUE THREAD

**Issue by Admonstrator** [stoo2000/membermap#13]
Hi there,

the "Why don't you submit the first one?" Button (if a marker group does not contain any entries) is broken because it will create an overlay window and in this window does not work due to some issues:

`Failed to parse SourceMap: https://www.cosvalley.de/membermap/markers/group/3-conventions/leaflet-src.map`
`VM3469:23 Uncaught TypeError: Cannot read property 'basemaps' of undefined`

If you create an entry manually by visiting the markers/submit page everything is working fine.

Nice update btw, really like this one! :+1:

**Comment by MartinAronsen** [comment]
Fixed :) 
769edc2924c837a649650aad1b91d7ed1f4ac0a0
