### ISSUE TITLE
Issue with HTTPS and iOS

### ISSUE THREAD

**Issue by MartinAronsen** [stoo2000/membermap#18]
Map does not appear to load on iOS devices when using HTTPS.

**Comment by MartinAronsen** [comment]
Unrelated to HTTPS. Safari (on both platforms) is more strict than Chrome.

**Comment by Admonstrator** [comment]
Can't confirm this issue. It's working fine for me by using HTTPS and OpenStreetMap.

**Comment by MartinAronsen** [comment]
Was an issue discovered while testing the next version :)
