### ISSUE TITLE
Membermap not compatible to some themes

### ISSUE THREAD

**Issue by Admonstrator** [stoo2000/membermap#22]
Hi there,

I'm some kind of confused because membermap seems to be not compatible to the theme I'm currently using. Some fields are not covered in content-boxes so you can't read them :(

I'm using the theme "chameleon" from [ipsfocus.com](http://www.ipsfocus.com/themes/chameleon/) and everything else is working fine - so this could be an issue with your code, couldn't it?

Here some screenshots:
[Screenshot 1](https://cosplayer.in/upload/1.png) | [Screenshot 2](https://cosplayer.in/upload/2.png)

Any idea how to fix this issue?

**Comment by MartinAronsen** [comment]
Are those two areas the only areas where this happens?

**Comment by Admonstrator** [comment]
I just checked out every page and found another one where the content-box seems to be broken:

[Screenshot 3](https://cosplayer.in/upload/3.png)

**Comment by MartinAronsen** [comment]
635313e64907362f3774ec0590806c46e8058954 and fa6a32174e719dc9226a4a126982bebbcc5f66c4 should fix this.
Can you double check the latter commit? Think adding "ipsContained" to that <article> is enough.

**Comment by Admonstrator** [comment]
Working, thanks! 👍
