### ISSUE TITLE
Can't change friendly url

### ISSUE THREAD

**Issue by Admonstrator** [stoo2000/membermap#23]
Hi there,

I've got an issue by changing a friendly url and I'm not aware if this is an bug within IPS or the custom app. I want to change the friendly URL /membermap/showfriends to /cosmap/showfriends. If I do so and save my edit IPS will insert "/membermap" in front of my change.

So I'm not able to change the friendly URL by replacing "membermap" with "cosmap" due to the fact that the system will use "/membermap/cosmap" as rewrite-base.

IPS support told me that this should be an issue with your app :-/

**Comment by MartinAronsen** [comment]
Is it just that FURL, or all of them? "showfriends" is not in use, so I wouldn't worry about that.

**Comment by Admonstrator** [comment]
All of them - excluding the base-FURL (/membermap)
Thats the only FURL I can change without problems.

**Comment by MartinAronsen** [comment]
Shouldn't that update all of them when changing that?

**Comment by Admonstrator** [comment]
Nope. You can change every FURL as you like. :(

**Comment by MartinAronsen** [comment]
> IPS support told me that this should be an issue with your app :-/
You can tell them Calendar behaves in the exact same way. Just tried changing "calendar/submit" to "coscal/submit", ended up as "calendar/coscal/submit".

**Comment by Admonstrator** [comment]
Mh, this does not happen in my installation. I changed all "calendar" FURLs too "coslendar" and everything was working fine. But as you said it seems to be a problem with IPS - will forward this.

**Comment by Admonstrator** [comment]
Ah, it happens in the actual version if IPS. I set the calendar-FURL in a earlier version.
Now this issue happens to me too. Thanks for your help!
