### ISSUE TITLE
'My Location' only for admins?

### ISSUE THREAD

**Issue by teamkonzept** [stoo2000/membermap#24]
Hi there,

our users want add their location in the member map but it seems only admins can use this feature. I added two screenshots, the first one from a logged in admin and the second one from a 'normal' user. As youo can see, the big green button isn't there. What can I do about this?

Kind regards.

![unbenannt1](https://cloud.githubusercontent.com/assets/22472839/18872199/72931c1c-84b9-11e6-9504-9d17abe0a665.JPG)
![unbenannt2](https://cloud.githubusercontent.com/assets/22472839/18872200/7294382c-84b9-11e6-97bb-992fc801c228.JPG)

**Comment by Admonstrator** [comment]
Hi there,

did you checked your permissions for the user group?
Only users with the correct permission are allowed to add entries.

Best regards

**Comment by teamkonzept** [comment]
Yes, every user group has the permission to use the member map.

**Comment by Admonstrator** [comment]
Please have a look into the permission per user group. There are 3 kind of permission afaik.
See Marker-Group, View Markers, Add Locations

**Comment by teamkonzept** [comment]
Ah, I found it. It was indeed with the user group settings.

You helped me very much, thank you!

This issue can be closed.
