### ISSUE TITLE
Reload issue if all calendars are enabled for sync

### ISSUE THREAD

**Issue by Admonstrator** [stoo2000/membermap#31]
Hi there,

thank you for this great calendar addon update - awesome function!

I just noticed that if you select to sync all calendars the map will stop working because every 1-2 secs the "rebuild cache" task will be triggered and the whole page will reload.

The issue does not exists if you choose to sync only 1 calendar.

Keep on the good work!

**Comment by MartinAronsen** [comment]
Can you add the following to constants.php:
`define( 'DEBUG_JS', TRUE );`
Then open the JS console and look at the log when it does this. Does it say "Cache Expired" right before it does the page refresh?

**Comment by Admonstrator** [comment]
Hi,

yupp, "cache expired" will be shown.
Now the issue effects the app even if I just choose one calendar to sync.

**Comment by MartinAronsen** [comment]
Can you upload the files in datastore/membermap_cache somewhere?

**Comment by Admonstrator** [comment]
I just send you a mail with the file attached.

**Comment by MartinAronsen** [comment]
I see, it’s actually selecting events that have ended as well. Will get this fixed tomorrow.
