### ISSUE TITLE
Request: Deep linking to maps

### ISSUE THREAD

**Issue by Admonstrator** [stoo2000/membermap#34]
Hi there

we are using different map marker groups (like "users", "events", ...) therefore it would be great if we could deep link to those maps. Maybe something like example.com/map/events to get only the event marker group enabled?

Specially for the new "calendar" marker group this would be great.

**Comment by MartinAronsen** [comment]
[membermap.tar.zip](https://github.com/stoo2000/membermap/files/706561/membermap.tar.zip)
Not gonna release a new version for this, so here's a rebuild of the latest version with this addition.
