### ISSUE TITLE
Task "does not work"

### ISSUE THREAD

**Issue by AndiKnight** [stoo2000/membermap#39]
Hi
![image](https://cloud.githubusercontent.com/assets/14957191/22406813/fefd4acc-e659-11e6-93f0-9a1d29965e25.png)

![image](https://cloud.githubusercontent.com/assets/14957191/22406824/337d6ff2-e65a-11e6-8018-725f6d24e851.png)

**Comment by MartinAronsen** [comment]
I can't push out a new release right now, but you can replace the file mentioned in the error with this one: https://github.com/stoo2000/membermap/blob/develop/sources/Map/Map.php

Let me know how it goes.
