### ISSUE TITLE
Not an issue: Thanks for your support!

### ISSUE THREAD

**Issue by Admonstrator** [stoo2000/membermap#41]
Hi there,

due to the fact that we are switching from IP.board to WordPress in the near future I would like to say thank you for your awesome support by keeping the membermap plugin up-to-date.

It was a pleasure to use your plugin & I really appreciate your work!
As we would say on eBay: Top seller, A++!

(A nice membermap plugin for WP would be awesome ... if you want to create some new 'things' ;-) )

Best regards & keep on the good work 👍

**Comment by MartinAronsen** [comment]
Sorry to see you go, Aaron 😢 
Thank you for sticking with us, and providing excellent feedback and willingness to try out experimental things, I have really appreciated that!

I have made some things for WP in the past, also a mapping solution, but just thinking about the WP framework makes me even sadder. 

Best of luck with your future endeavor 😄
