### ISSUE TITLE
Map Shows Partial Display

### ISSUE THREAD

**Issue by johncourtland** [stoo2000/membermap#43]
I am currently running IPS Community Suite v4.1.19.1 and Member Map 3.1.9. Base IP theme is only modified with a header image and background color.

I uploaded and started a clean fresh instance of Member Map, this was not an upgrade, and when I went to view the map, it is showing as only a partial view.
I have tried a few things, disabled plugins for conflicts, disabled other applications for conflicts, cleared system cache, cleared desktop pc cache, cleared browser cache, test in Chrome, FF, IE, Vivaldi, and Opera, and the same partial map is being displayed. I signed in as test member, and partial view was still displayed.

Thank you for considering this bug report. Member Map is not being displayed for obvious reasons, I can supply admin credentials for login.

John
![capture](https://cloud.githubusercontent.com/assets/12961228/24800230/28f1b686-1b54-11e7-8f4e-3138bb8a0f0c.JPG)

**Comment by MartinAronsen** [comment]
I've seen this before, and it was caused by a custom advert placed incorrectly.

If you send me a login I can have a look for you.

**Comment by MartinAronsen** [comment]
Was an issue with the plugin "Advanced Footer".
