### ISSUE TITLE
Marker colour per group

### ISSUE THREAD

**Issue by MartinAronsen** [stoo2000/membermap#6]

**Comment by nonibanacu** [comment]
Hello Martin,

Is it possible to install this plugin on a live or dev board?

**Comment by MartinAronsen** [comment]
That beta version will soon make an appearance on the [Marketplace](https://community.invisionpower.com/files/file/7894-member-map-beta/)

**Comment by nonibanacu** [comment]
Under your name or stoo's name?

**Comment by nonibanacu** [comment]
aha,.. will it be the link from the marketplace?

**Comment by MartinAronsen** [comment]
Yeah, that would be the link.
