### ISSUE TITLE
Area counter acting weird

### ISSUE THREAD

**Issue by Admonstrator** [stoo2000/membermap#8]
Hi there,

in the current beta (3?) the "area" counter is acting some kind of weird. If you zoom out the page all areas will be shrink to just one big area with the number of locations in it. But in the actual beta this main area will not get deleted if you zoom in.

Maybe it's better to understand if I add an image of this issue:
https://admonstrator.de/index.php/s/uF4t616Ypb5K5GA

As you can see there are 104 locations within Germany.
If you zoom in this big number will not get invisible ... so you always have this 104 locations in view - even zoomed in.

After hitting the refresh markers button this issue seems to be vanished but only for this page view. If you reload the page everything is weird again. Check it out on www.cosmap.de

Thanks!

**Comment by MartinAronsen** [comment]
Working as expected using Google Chrome on OS X.
I'll update the MarkerCluster plugin, and we'll see if that solves it.

**Comment by Admonstrator** [comment]
Will there be a installable tar in the next fews days or should I just clone the repo?

**Comment by stoo2000** [comment]
No, you should never do that. Always use the marketplace version, the repos never contains the compiled application.

**Comment by Admonstrator** [comment]
Good to know ;) Any idea when the next beta will be ready?

**Comment by Admonstrator** [comment]
Bug still exists in the actual version with up-to-date IPS.

**Comment by MartinAronsen** [comment]
I were able to see it for a brief moment on your site, but it went away as soon as the zoom level changed.
Are you seeing this all the time?

And you never mentioned your browser and device versions.

**Comment by Admonstrator** [comment]
Hi,
it's weird. Sometimes I can see it all the time, sometimes only after reloading the page.

Currently I'm using Google Chrome 48.0.2564.103 on Windows 10 Build 10586.71

**Comment by MartinAronsen** [comment]
Do you see any errors in the console (except the "Mixed Content" warnings)?

**Comment by Admonstrator** [comment]
Nope.

**Comment by MartinAronsen** [comment]
I'll do my best in figuring out why this is happening, but I can't really guarantee anything unless I'm able to reproduce it locally.

**Comment by Admonstrator** [comment]
No problem, it's not critical.

**Comment by MartinAronsen** [comment]
I ditched a plugin that might have interfered with MarkerCluster, OverlappingMarkerSpiderfier. It hasn't been updated for over 3 years, and MarkerCluster already had that functionality.

**Comment by MartinAronsen** [comment]
Can you confirm that this was fixed by the last update?

**Comment by Admonstrator** [comment]
Yes, everything is working now ~ thanks!
