### ISSUE TITLE
How to change default map provider?

### ISSUE THREAD

**Issue by Admonstrator** [stoo2000/membermap#9]
In the last version it was no problem for me to add openstreetmap as a default provider. But in this actual version I'm not able to modify this behavior again.

Could you provide me a short manual how to change the default map provider and remove the other providers? I don't want to have 4 map provider, just openstreetmap.

Thanks! :+1:

**Comment by MartinAronsen** [comment]
This is something I want to add to a future version.
There's no quick and easy way to modify this, as the javascript files are compressed and compiled.

**Comment by MartinAronsen** [comment]
de5d67e06fc4154f1ae317dbc4627894a5efca76
